# -*- coding: utf-8 -*-
"""internal assessment-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_RprECwB55OPbr0CDtg0Mx2OjHueB-vD
"""

#1
print("enter length and breadth")
l=float(input())
b=float(input())
print(l*b)

#2
print("body mass index")
print("enter weight in kgs and height in mts")
w=int(input())
h=float(input())
print(w/(h**2))

#3
students={}
print("number of entries?")
x=int(input())
while x>0:
  k=input()
  v=input()
  students[k]=v
  x-=1
print(students)

#4
print("enter your age")
age=int(input())
if age <18:
  print("minor")
elif age > 60:
  print("senior")
else:
  print("adult")

#5
for i in range(51):
  if i%2==0:
    print(i)

#6
password="password"
p='0'
while p != password:
  print("please enter correct password")
  p=input()
print(p+" is correct ")

#7
def avg(l,b):
  x=0
  sum=0
  for g in l:
    sum=sum+g
  x=sum/b
  return x
l=[]
c=int(input())
b=c
while c>0:
  x=int(input())
  l.append(x)
  c-=1
print(avg(l,b))

#8
def vowel_count(s):
  x=0
  for i in s:
    if i in ('a','e','i','o','u'):
      x+=1
  return x
s=input()
print(vowel_count(s))

#9
import datetime as d
da=d.datetime
print(da)

#10
try:
  a=input()
  b=int(input())
  print(a+b)
except Exception :
  print("non numeric inputs cannot be added")

#11
try:
  x=int(input())
  print(x)
except Exception:
  print("Value Error")

#12
def div(a,b):
  try:
    print( a/b)
  except ZeroDivisionError :
    print("division with zero is not possible")

a=int(input())
b=int(input())
div(a,b)

#13
#with open("C:\Users\tushar.paraselli.lv\Desktop\13.ipnb")
textfile=open("/content/13.txt",'w')
textfile.writelines("Hello,Python ")
textfile.close()

textfile=open("/content/13.txt",'r')
textfile.close()

textfile=open("/content/13.txt",'a')
textfile.writelines("Hello,World")
textfile.close()